ALTER TABLE "StyleExtractionTask"
ADD COLUMN IF NOT EXISTS "promptTokens" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "StyleExtractionTask"
ADD COLUMN IF NOT EXISTS "completionTokens" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "StyleExtractionTask"
ADD COLUMN IF NOT EXISTS "totalTokens" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "StyleExtractionTask"
ADD COLUMN IF NOT EXISTS "llmCallCount" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "StyleExtractionTask"
ADD COLUMN IF NOT EXISTS "lastTokenRecordedAt" TIMESTAMP;

