import type {
  AntiAiRuleType,
  AntiAiSeverity,
  CharacterRules,
  LanguageRules,
  NarrativeRules,
  RhythmRules,
} from "@ai-novel/shared/types/styleEngine";

export interface DefaultTemplateDefinition {
  key: string;
  name: string;
  description: string;
  category: string;
  tags: string[];
  applicableGenres: string[];
  analysisMarkdown: string;
  narrativeRules: NarrativeRules;
  characterRules: CharacterRules;
  languageRules: LanguageRules;
  rhythmRules: RhythmRules;
  defaultAntiAiRuleKeys: string[];
}

export interface DefaultAntiAiRuleDefinition {
  key: string;
  name: string;
  type: AntiAiRuleType;
  severity: AntiAiSeverity;
  description: string;
  detectPatterns: string[];
  rewriteSuggestion: string;
  promptInstruction: string;
  autoRewrite: boolean;
  enabled: boolean;
  globalBaselineEnabled: boolean;
}

export interface DefaultStarterStyleProfileDefinition {
  key: string;
  templateKey: string;
  name: string;
  description: string;
}

export const DEFAULT_STYLE_TEMPLATES: DefaultTemplateDefinition[] = [
  {
    key: "vn-market-tension",
    name: "Việt ngữ chợ búa căng ngầm",
    description: "Giữ nhịp đời thường Việt Nam, mùi vị chợ búa và áp lực ngầm trong lời nói ngắn, sắc.",
    category: "Việt ngữ đời thường",
    tags: ["tiếng Việt", "đời thường", "căng ngầm", "chợ búa"],
    applicableGenres: ["đô thị", "hiện thực", "hình sự"],
    analysisMarkdown: "Tập trung vào chi tiết đời thường Việt Nam, đối thoại ngắn giàu lực, ít giải thích tâm lý trực tiếp và giữ cảm giác người thật đang sống trong cảnh.",
    narrativeRules: {
      progressionMode: "scene_immersion",
      sceneUnitPattern: ["chi tiết đời thường", "hành động nhỏ", "lời đáp ngắn", "áp lực tăng dần"],
      multiPov: false,
      looping: false,
      endingStyle: "pressure_continue",
      summary: "Đẩy cảnh bằng sinh hoạt, va chạm lời nói và nguy cơ treo lơ lửng ngay trong đời thường.",
    },
    characterRules: {
      allowSelfReflection: false,
      emotionExpression: "behavior_only",
      defenseMechanisms: ["miệng cứng", "né tránh", "đánh trống lảng"],
      facePriority: true,
      dialogueStyle: "short_colloquial",
      summary: "Nhân vật không tự giảng cảm xúc; trạng thái lộ ra qua động tác, nhịp nói và cách giữ thể diện.",
    },
    languageRules: {
      register: "colloquial",
      roughness: 0.7,
      allowIncompleteSentences: true,
      allowSwearing: true,
      sentenceVariation: "high",
      allowUselessDetails: true,
      summary: "Tiếng Việt gọn, sống, hơi ráp; cho phép tạp âm sinh hoạt và khẩu ngữ bản địa.",
    },
    rhythmRules: {
      pace: "medium_fast",
      paragraphDensity: "medium_high",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "Nhịp cảnh gọn, không đứng lại giải thích; ưu tiên động tác và phản ứng cụ thể.",
    },
    defaultAntiAiRuleKeys: [
      "forbid-explicit-psychology",
      "forbid-ending-elevation",
      "risk-dialogue-too-functional",
      "encourage-life-noise",
      "encourage-hard-mouth-compensation",
    ],
  },
  {
    key: "vn-knife-edge-dialogue",
    name: "Việt ngữ đối thoại dao mỏng",
    description: "Dồn lực vào đối thoại ngắn, giấu ý dưới bề mặt và để xung đột đi bằng nhịp đáp trả.",
    category: "Việt ngữ đối thoại",
    tags: ["tiếng Việt", "đối thoại", "ẩn ý", "xung đột"],
    applicableGenres: ["ngôn tình", "đô thị", "hình sự"],
    analysisMarkdown: "Giữ câu ngắn, giảm lời giải thích, để quyền lực và cảm xúc lệch nhau trong từng lượt đáp.",
    narrativeRules: {
      progressionMode: "relationship_push_pull",
      sceneUnitPattern: ["câu chạm", "ẩn ý", "đỡ đòn", "lệch nhịp cảm xúc"],
      multiPov: false,
      looping: false,
      endingStyle: "emotional_hook",
      summary: "Cảnh sống bằng các lượt nói ngắn có lực, không thuyết minh hộ quan hệ.",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "subtext",
      defenseMechanisms: ["thử phản ứng", "nói cạnh", "giữ mặt"],
      facePriority: true,
      dialogueStyle: "subtext_heavy",
      summary: "Cảm xúc nằm dưới lớp lời nói; nhân vật thường không nói đúng điều mình đau hoặc muốn.",
    },
    languageRules: {
      register: "natural",
      roughness: 0.45,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "high",
      allowUselessDetails: false,
      summary: "Ưu tiên câu ngắn, tự nhiên, có lực cắt; tránh văn mẫu và giải thích thừa.",
    },
    rhythmRules: {
      pace: "fast",
      paragraphDensity: "medium",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "Đối thoại rơi nhanh, xen phản ứng cơ thể ngắn để giữ điện áp cảnh.",
    },
    defaultAntiAiRuleKeys: [
      "forbid-direct-preaching",
      "forbid-explicit-psychology",
      "risk-dialogue-too-functional",
      "risk-repeated-sentence-structure",
    ],
  },
  {
    key: "vn-soft-daily-healing",
    name: "Việt ngữ đời thường mềm và ấm",
    description: "Giữ nhịp chậm vừa, chi tiết Việt Nam gần gũi và cảm xúc lộ qua việc nhỏ hơn là câu to.",
    category: "Việt ngữ đời thường",
    tags: ["tiếng Việt", "đời thường", "ấm", "chữa lành"],
    applicableGenres: ["đời thường", "chữa lành", "đô thị"],
    analysisMarkdown: "Lấy cảm giác sống thật làm nền, dùng chi tiết nhỏ, lời nói tự nhiên và khoảng lặng ngắn để tích cảm xúc.",
    narrativeRules: {
      progressionMode: "scene_immersion",
      sceneUnitPattern: ["việc nhỏ", "chi tiết cảm giác", "phản ứng nhẹ", "dư âm"],
      multiPov: false,
      looping: false,
      endingStyle: "soft_open",
      summary: "Cho cảnh thở bằng sinh hoạt nhỏ và quan hệ gần, không ép phải có cú đẩy lớn mỗi đoạn.",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "light_behavior",
      defenseMechanisms: ["né nhẹ", "im lặng", "cười trừ"],
      facePriority: false,
      dialogueStyle: "daily_natural",
      summary: "Người nói như người thật; cảm xúc hiện qua cách chăm, tránh, chờ và đỡ nhau.",
    },
    languageRules: {
      register: "colloquial",
      roughness: 0.2,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "medium_high",
      allowUselessDetails: true,
      summary: "Giữ tiếng Việt mềm, tự nhiên, gần hơi thở sinh hoạt, không bóng bẩy quá mức.",
    },
    rhythmRules: {
      pace: "slow",
      paragraphDensity: "medium",
      allowFragmentedFlow: true,
      actionOverExplanation: false,
      summary: "Nhịp chậm vừa, đủ lặng để thấm nhưng không được đứng yên vô cớ.",
    },
    defaultAntiAiRuleKeys: [
      "forbid-ending-elevation",
      "forbid-theme-summary",
      "risk-even-paragraph-length",
      "encourage-life-noise",
    ],
  },
  {
    key: "vn-grit-first-person",
    name: "Việt ngữ ngôi một gai góc",
    description: "Ngôi kể thứ nhất sắc, hơi thô, phản ứng nhanh và giữ cảm giác người kể đang tự chống đỡ mình.",
    category: "Việt ngữ ngôi một",
    tags: ["tiếng Việt", "ngôi một", "gai góc", "hiện thực"],
    applicableGenres: ["hiện thực", "đô thị", "trưởng thành"],
    analysisMarkdown: "Dùng ngôi một để kéo gần thân thể và cảm giác, nhưng tránh độc thoại giải thích; để người kể bộc lộ qua phản ứng cụt và cách tự chữa thẹn.",
    narrativeRules: {
      progressionMode: "time_sequence",
      sceneUnitPattern: ["phản ứng thân thể", "quan sát ngắn", "tự chống đỡ", "cú va hiện thực"],
      multiPov: false,
      looping: true,
      endingStyle: "unresolved",
      summary: "Ngôi một phải có hơi thở, có xước, có lệch, chứ không được sạch như kể báo cáo.",
    },
    characterRules: {
      allowSelfReflection: false,
      emotionExpression: "behavior_only",
      defenseMechanisms: ["tự nhét lời xuống", "miệng cứng", "chuyển ý đột ngột"],
      facePriority: true,
      dialogueStyle: "short_colloquial",
      summary: "Người kể không nói rõ nỗi đau; họ để lộ qua thân thể, nhịp nghĩ vụn và cách nói cộc.",
    },
    languageRules: {
      register: "colloquial",
      roughness: 0.8,
      allowIncompleteSentences: true,
      allowSwearing: true,
      sentenceVariation: "high",
      allowUselessDetails: true,
      summary: "Giữ tiếng kể gần miệng nói thật, không làm mịn quá tay.",
    },
    rhythmRules: {
      pace: "balanced",
      paragraphDensity: "high",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "Để ý nhịp hụt, nhịp cắn chữ, nhịp tự ngắt, tạo cảm giác đang sống ngay trong cảnh.",
    },
    defaultAntiAiRuleKeys: [
      "forbid-explicit-psychology",
      "forbid-ending-elevation",
      "encourage-reality-gap",
      "encourage-hard-mouth-compensation",
    ],
  },
  {
    key: "bottom-loop-reality",
    name: "底层循环现实流",
    description: "通过碎片化生活与反复落空表现人物困境。",
    category: "现实流",
    tags: ["第一人称", "口语化", "碎片叙事"],
    applicableGenres: ["都市", "现实", "成长"],
    analysisMarkdown: "以时间推进和现实落差构成叙事张力，结尾不解决核心困境。",
    narrativeRules: {
      progressionMode: "time_sequence",
      sceneUnitPattern: ["行为", "落差", "自我合理化"],
      multiPov: false,
      looping: true,
      endingStyle: "unresolved",
      summary: "以碎片化生活推进，不做总括式回顾。",
    },
    characterRules: {
      allowSelfReflection: false,
      emotionExpression: "behavior_only",
      defenseMechanisms: ["嘴硬", "转移", "自我合理化"],
      facePriority: true,
      dialogueStyle: "short_colloquial",
      summary: "人物情绪通过动作和嘴硬表达。",
    },
    languageRules: {
      register: "colloquial",
      roughness: 0.8,
      allowIncompleteSentences: true,
      allowSwearing: true,
      sentenceVariation: "high",
      allowUselessDetails: true,
      summary: "语言粗粝、口语化，允许生活杂音。",
    },
    rhythmRules: {
      pace: "medium_fast",
      paragraphDensity: "high",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "段落密实，动作先于解释。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-explicit-psychology",
      "forbid-ending-elevation",
      "encourage-useless-action",
      "encourage-reality-gap",
      "encourage-hard-mouth-compensation",
    ],
  },
  {
    key: "power-up-escalation",
    name: "爽文递进推进流",
    description: "持续升级冲突和收益点，强化目标推进与爽点兑现。",
    category: "爽文流",
    tags: ["推进感", "收益点", "冲突升级"],
    applicableGenres: ["都市", "玄幻", "热血"],
    analysisMarkdown: "每段都要有目标推进或爽点兑现，保持明确因果和节奏抬升。",
    narrativeRules: {
      progressionMode: "goal_driven",
      sceneUnitPattern: ["目标", "阻碍", "压制", "反转收益"],
      multiPov: false,
      looping: false,
      endingStyle: "hook",
      summary: "围绕目标推进，尽快兑现局部收益。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "dialogue_and_action",
      defenseMechanisms: [],
      facePriority: false,
      dialogueStyle: "direct",
      summary: "角色表达直接，情绪跟随胜负切换。",
    },
    languageRules: {
      register: "direct",
      roughness: 0.55,
      allowIncompleteSentences: false,
      allowSwearing: false,
      sentenceVariation: "medium",
      allowUselessDetails: false,
      summary: "句式清晰，减少无效分散信息。",
    },
    rhythmRules: {
      pace: "fast",
      paragraphDensity: "medium",
      allowFragmentedFlow: false,
      actionOverExplanation: true,
      summary: "优先冲突和结果，少停留。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-theme-summary",
      "risk-dialogue-too-functional",
      "risk-three-paragraphs-exposition",
    ],
  },
  {
    key: "suspense-pressure",
    name: "悬疑压迫递增流",
    description: "通过信息遮蔽、细节异常和压力叠加制造不安感。",
    category: "悬疑流",
    tags: ["压迫感", "信息差", "异常细节"],
    applicableGenres: ["悬疑", "惊悚", "现实"],
    analysisMarkdown: "以异常细节、信息差和节奏收束推动悬念层层加压。",
    narrativeRules: {
      progressionMode: "mystery_escalation",
      sceneUnitPattern: ["现场细节", "异常", "误判", "新风险"],
      multiPov: false,
      looping: false,
      endingStyle: "suspense",
      summary: "优先制造信息缺口和压迫氛围。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "reaction_only",
      defenseMechanisms: ["压抑"],
      facePriority: false,
      dialogueStyle: "restrained",
      summary: "角色反应克制，恐惧通过反应显现。",
    },
    languageRules: {
      register: "restrained",
      roughness: 0.45,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "medium_high",
      allowUselessDetails: true,
      summary: "细节精确，保留少量噪音增强现场感。",
    },
    rhythmRules: {
      pace: "medium",
      paragraphDensity: "medium_high",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "通过节奏收束和信息延迟制造压力。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-explicit-psychology",
      "forbid-theme-summary",
      "risk-even-paragraph-length",
      "encourage-reality-gap",
    ],
  },
  {
    key: "emotional-tension",
    name: "情绪拉扯流",
    description: "通过错位表达、停顿和误读制造关系张力。",
    category: "情感流",
    tags: ["误读", "拉扯", "停顿感"],
    applicableGenres: ["言情", "都市", "群像"],
    analysisMarkdown: "人物不直说核心情绪，靠误读、停顿和反应推动关系变化。",
    narrativeRules: {
      progressionMode: "relationship_push_pull",
      sceneUnitPattern: ["动作", "言外之意", "误读", "回避"],
      multiPov: false,
      looping: false,
      endingStyle: "emotional_hook",
      summary: "以关系错位推进，而非直接说明。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "subtext",
      defenseMechanisms: ["回避", "试探", "嘴硬"],
      facePriority: true,
      dialogueStyle: "subtext_heavy",
      summary: "情绪通过停顿、动作和言外之意体现。",
    },
    languageRules: {
      register: "natural",
      roughness: 0.35,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "high",
      allowUselessDetails: true,
      summary: "语言自然，允许留白与停顿。",
    },
    rhythmRules: {
      pace: "medium_slow",
      paragraphDensity: "medium",
      allowFragmentedFlow: true,
      actionOverExplanation: false,
      summary: "给关系反应留空间，但避免空洞抒情。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-direct-preaching",
      "forbid-ending-elevation",
      "risk-dialogue-too-functional",
      "encourage-useless-action",
    ],
  },
  {
    key: "ensemble-weave",
    name: "群像交织流",
    description: "以多人行动线和视角差异交织推进事件。",
    category: "群像流",
    tags: ["多角色", "交织", "信息流动"],
    applicableGenres: ["群像", "都市", "悬疑"],
    analysisMarkdown: "多角色并行推进，但每个角色的表达和认知范围必须区分清楚。",
    narrativeRules: {
      progressionMode: "multi_thread",
      sceneUnitPattern: ["角色动作", "局部信息", "交叉影响"],
      multiPov: true,
      looping: false,
      endingStyle: "cross_hook",
      povSwitchStyle: "controlled",
      summary: "多线并进，但视角切换要受控。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "mixed",
      defenseMechanisms: [],
      facePriority: false,
      dialogueStyle: "distinct_by_role",
      summary: "不同角色口吻必须拉开差异。",
    },
    languageRules: {
      register: "flexible",
      roughness: 0.45,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "high",
      allowUselessDetails: false,
      summary: "保持角色差异，避免所有人说话一样。",
    },
    rhythmRules: {
      pace: "balanced",
      paragraphDensity: "medium",
      allowFragmentedFlow: false,
      actionOverExplanation: true,
      summary: "多线交织但节奏不乱。",
    },
    defaultAntiAiRuleKeys: [
      "risk-dialogue-too-functional",
      "risk-repeated-sentence-structure",
      "forbid-theme-summary",
    ],
  },
  {
    key: "immersive-daily",
    name: "日常浸没流",
    description: "通过生活细节和细微情绪变化建立持续沉浸感。",
    category: "日常流",
    tags: ["生活感", "沉浸", "细碎细节"],
    applicableGenres: ["日常", "治愈", "都市"],
    analysisMarkdown: "允许保留生活性动作和无效信息，但核心情绪仍要通过场景自然流出。",
    narrativeRules: {
      progressionMode: "scene_immersion",
      sceneUnitPattern: ["动作", "环境", "关系反应"],
      multiPov: false,
      looping: false,
      endingStyle: "soft_open",
      summary: "重场景体验和关系温度。",
    },
    characterRules: {
      allowSelfReflection: true,
      emotionExpression: "light_behavior",
      defenseMechanisms: [],
      facePriority: false,
      dialogueStyle: "daily_natural",
      summary: "人物表达自然，不用高强度戏剧句。",
    },
    languageRules: {
      register: "colloquial",
      roughness: 0.25,
      allowIncompleteSentences: true,
      allowSwearing: false,
      sentenceVariation: "medium_high",
      allowUselessDetails: true,
      summary: "保留生活细节和杂音，不追求工整。",
    },
    rhythmRules: {
      pace: "slow",
      paragraphDensity: "medium",
      allowFragmentedFlow: true,
      actionOverExplanation: false,
      summary: "慢节奏沉浸，但避免空转。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-ending-elevation",
      "risk-even-paragraph-length",
      "encourage-useless-action",
    ],
  },
  {
    key: "cold-professional",
    name: "冷峻专业流",
    description: "以专业事实和行业细节压住情绪，形成克制压力感。",
    category: "专业流",
    tags: ["专业细节", "克制", "事实压情绪"],
    applicableGenres: ["职场", "现实", "悬疑"],
    analysisMarkdown: "行业事实和程序细节优先，情绪不直说，信息密度高于抒情密度。",
    narrativeRules: {
      progressionMode: "fact_driven",
      sceneUnitPattern: ["事实", "动作", "专业判断", "后果"],
      multiPov: false,
      looping: false,
      endingStyle: "pressure_continue",
      summary: "让专业事实承担叙事重量。",
    },
    characterRules: {
      allowSelfReflection: false,
      emotionExpression: "suppressed",
      defenseMechanisms: ["克制"],
      facePriority: false,
      dialogueStyle: "informational",
      summary: "情绪藏在专业动作和事实选择里。",
    },
    languageRules: {
      register: "professional",
      roughness: 0.2,
      allowIncompleteSentences: false,
      allowSwearing: false,
      sentenceVariation: "medium",
      allowUselessDetails: false,
      summary: "术语和事实优先，避免廉价金句。",
    },
    rhythmRules: {
      pace: "balanced",
      paragraphDensity: "medium_high",
      allowFragmentedFlow: false,
      actionOverExplanation: true,
      summary: "信息密度高，但不铺张解释。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-direct-preaching",
      "forbid-theme-summary",
      "risk-repeated-sentence-structure",
    ],
  },
  {
    key: "absurd-dark-humor",
    name: "荒诞黑色幽默流",
    description: "通过反差、冷感观察和荒诞细节制造黑色幽默。",
    category: "黑色幽默",
    tags: ["荒诞", "反差", "冷感"],
    applicableGenres: ["都市", "黑色幽默", "现实"],
    analysisMarkdown: "用反差和荒诞细节放大现实困境，笑点和压迫感同时存在。",
    narrativeRules: {
      progressionMode: "contrast_driven",
      sceneUnitPattern: ["现实细节", "荒诞偏差", "冷反应"],
      multiPov: false,
      looping: false,
      endingStyle: "bitter_aftertaste",
      summary: "依赖反差和冷感观察，而非热闹吐槽。",
    },
    characterRules: {
      allowSelfReflection: false,
      emotionExpression: "deadpan",
      defenseMechanisms: ["自嘲", "转移"],
      facePriority: true,
      dialogueStyle: "deadpan_colloquial",
      summary: "情绪藏在冷反应和嘴硬里。",
    },
    languageRules: {
      register: "colloquial",
      roughness: 0.5,
      allowIncompleteSentences: true,
      allowSwearing: true,
      sentenceVariation: "high",
      allowUselessDetails: true,
      summary: "允许夹带荒诞杂质和冷幽默节奏。",
    },
    rhythmRules: {
      pace: "balanced",
      paragraphDensity: "medium_high",
      allowFragmentedFlow: true,
      actionOverExplanation: true,
      summary: "反差点要快落地，不要解释笑点。",
    },
    defaultAntiAiRuleKeys: [
      "forbid-explicit-psychology",
      "forbid-ending-elevation",
      "encourage-reality-gap",
      "encourage-hard-mouth-compensation",
    ],
  },
];

export const DEFAULT_STARTER_STYLE_PROFILES: DefaultStarterStyleProfileDefinition[] = [
  {
    key: "starter-vn-market",
    templateKey: "vn-market-tension",
    name: "Mặc định Việt ngữ chợ búa căng ngầm",
    description: "Dùng khi bạn muốn giọng Việt sống, mùi cảnh rõ và áp lực ngầm đi bằng đời thường thay vì bằng lời giải thích.",
  },
  {
    key: "starter-vn-dialogue",
    templateKey: "vn-knife-edge-dialogue",
    name: "Mặc định Việt ngữ đối thoại dao mỏng",
    description: "Dùng khi trọng tâm là lời thoại ngắn, ẩn ý mạnh, xung đột đẩy bằng từng lượt đáp qua lại.",
  },
  {
    key: "starter-vn-soft-daily",
    templateKey: "vn-soft-daily-healing",
    name: "Mặc định Việt ngữ đời thường mềm và ấm",
    description: "Dùng cho cảnh đời thường, chữa lành hoặc quan hệ gần, ưu tiên cảm giác sống thật và dư âm nhẹ.",
  },
  {
    key: "starter-vn-first-person",
    templateKey: "vn-grit-first-person",
    name: "Mặc định Việt ngữ ngôi một gai góc",
    description: "Dùng cho ngôi kể thứ nhất cần gần thân thể, hơi ráp, có sức chống đỡ và cảm giác người thật đang kể.",
  },
  {
    key: "starter-power-up",
    templateKey: "power-up-escalation",
    name: "我的默认爽文推进写法",
    description: "适合第一次开书先跑顺目标推进、爽点兑现和章节收益点，后续可以直接在此基础上微调。",
  },
  {
    key: "starter-suspense",
    templateKey: "suspense-pressure",
    name: "我的默认悬疑压迫写法",
    description: "适合异常、规则、调查和危险逼近类故事，先帮你把压迫感和信息差稳住。",
  },
  {
    key: "starter-emotional",
    templateKey: "emotional-tension",
    name: "我的默认情绪拉扯写法",
    description: "适合关系推进、误读拉扯和情绪兑现类故事，先有一套能直接开写的关系型表达底座。",
  },
  {
    key: "starter-daily",
    templateKey: "immersive-daily",
    name: "我的默认日常浸没写法",
    description: "适合治愈、陪伴、生活经营和轻缓成长类故事，优先保证生活感和沉浸感。",
  },
];

export const DEFAULT_ANTI_AI_RULES: DefaultAntiAiRuleDefinition[] = [
  {
    key: "forbid-explicit-psychology",
    name: "Cam giai thich tam ly truc tiep",
    type: "forbidden",
    severity: "high",
    description: "Khong dien giai tam ly bang cac cau kieu anh cam thay, co nhan ra, han hieu ra.",
    detectPatterns: ["anh cam thay", "co cam thay", "han cam thay", "anh nhan ra", "co nhan ra", "han hieu ra"],
    rewriteSuggestion: "Doi phan giai thich tam ly thanh hanh dong, ngu khi, nhip ngat, phan ung moi truong hoac hau qua cu the.",
    promptInstruction: "Khong giai thich truc tiep tam ly nhan vat. Trang thai nhan vat phai lo ra qua hanh vi, dong tac, loi noi hoac phan ung cua hoan canh.",
    autoRewrite: true,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "forbid-ending-elevation",
    name: "Cam nang chu de o cuoi doan",
    type: "forbidden",
    severity: "high",
    description: "Khong dung cau ket tong luan de day chu de hoac rut ra y nghia o cuoi doan hay cuoi canh.",
    detectPatterns: ["cuoc doi von la", "so menh roi se", "noi cho cung", "rot cuoc thi", "do chinh la"],
    rewriteSuggestion: "Bo cau nang chu de, keo doan ket ve hanh dong cu the, hien truong, hoac mot tinh the con treo.",
    promptInstruction: "Khong nang chu de hay tong ket o cuoi doan. Phan ket phai roi lai vao tinh canh cu the.",
    autoRewrite: true,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "forbid-theme-summary",
    name: "Cam tong ket chu de",
    type: "forbidden",
    severity: "high",
    description: "Khong bien doan van thanh noi chot y trung tam hay rut ra bai hoc doi song cho nguoi doc.",
    detectPatterns: ["dieu do cho thay", "dieu ay co nghia la", "noi cho cung", "that ra chinh la"],
    rewriteSuggestion: "Xoa cau tong ket chu de, de y nghia tu noi len tu su kien va ket qua.",
    promptInstruction: "Dung tong ket chu de va dung thay nguoi doc rut ra tu tuong trung tam.",
    autoRewrite: true,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "forbid-direct-preaching",
    name: "Cam noi dao ly truc dien",
    type: "forbidden",
    severity: "medium",
    description: "Khong de tac gia thay nhan vat hoac thay nguoi doc phan xet gia tri roi giang dao ly thang mat.",
    detectPatterns: ["chung ta deu nen", "con nguoi phai hoc cach", "dieu that su quan trong la"],
    rewriteSuggestion: "Doi sang tinh huong cu the hoac loi thoai co ngu canh, tranh giang dao ly truu tuong.",
    promptInstruction: "Khong noi dao ly truc tiep hay phan xet gia tri. Hay de y nghia nam trong chinh su kien.",
    autoRewrite: true,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "risk-even-paragraph-length",
    name: "Do dai doan qua deu",
    type: "risk",
    severity: "medium",
    description: "Do dai doan va nhip dieu qua quan binh de tao cam giac van AI, van mau.",
    detectPatterns: ["doan qua deu", "nhip qua deu"],
    rewriteSuggestion: "Pha nhip do dai doan, de cau va doan co len xuong tu nhien hon.",
    promptInstruction: "Tranh de moi doan deu qua gon, qua can va giong bai van mau.",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "risk-three-paragraphs-exposition",
    name: "Ba doan lien chi giai thich",
    type: "risk",
    severity: "high",
    description: "Nhieu doan lien chi co phan giai thich, khong co hanh dong hay phan ung hien truong, se lam yeu cam giac dang song trong canh.",
    detectPatterns: ["lien tuc giai thich", "khong co hanh dong"],
    rewriteSuggestion: "Chen hanh dong, doi thoai, hoac phan hoi tu moi truong de cat bot phan thuyet minh keo dai.",
    promptInstruction: "Tranh de nhieu doan lien chi toan giai thich ma thieu hanh dong hoac doi thoai.",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "risk-dialogue-too-functional",
    name: "Doi thoai chi lam nhiem vu day cot truyen",
    type: "risk",
    severity: "medium",
    description: "Doi thoai chi truyen thong tin ma thieu giong nhan vat va nhieu doi thuong se rat may moc.",
    detectPatterns: ["noi cho anh biet", "bay gio chung ta phai", "tiep theo la"],
    rewriteSuggestion: "Bo sung ngap ngung, noi vong, khac biet ngu khi va ca nhung thong tin khong hoan toan huu dung.",
    promptInstruction: "Dung de doi thoai chi ganh chuc nang day tinh tiet. Hay giu giong nhan vat va tieng on doi thuong.",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "risk-repeated-sentence-structure",
    name: "Cau truc cau lap qua nhieu",
    type: "risk",
    severity: "medium",
    description: "Nhieu cau noi tiep co cung nhip va cung kieu mo dau se tao cam giac co khi.",
    detectPatterns: ["dau tien", "sau do", "tiep theo", "cuoi cung"],
    rewriteSuggestion: "Keo gian do dai cau va doi cach mo cau de pha deu cau truc.",
    promptInstruction: "Canh giac voi lap cau truc cau lien tiep va kieu viet can hang may moc.",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: true,
  },
  {
    key: "encourage-useless-action",
    name: "Khuyen khich tieu dong tac doi thuong",
    type: "encourage",
    severity: "low",
    description: "Nen them cac tieu dong tac that nhung khong truc tiep day chu tuyen de tang cam giac nguoi that.",
    detectPatterns: [],
    rewriteSuggestion: "Them nhung dong tac nho nhu xoa tay, bat lua, keo ghe, chinh co ao hoac gap lai do vat.",
    promptInstruction: "Uu tien them cac dong tac nho chan that nhung khong truc tiep day chu tuyen de tang suc song doi thuong.",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
  {
    key: "encourage-reality-gap",
    name: "Khuyen khich do venh giua ky vong va thuc te",
    type: "encourage",
    severity: "low",
    description: "Nen tao khoang lech giua dieu nhan vat tuong se xay ra va ket qua that nhan duoc.",
    detectPatterns: [],
    rewriteSuggestion: "Bu vao doan chenh giua ky vong ban dau cua nhan vat va ket qua thuc te dang xay ra.",
    promptInstruction: "Uu tien tao do venh thuc te de ky vong cua nhan vat khong trung khit hoan toan voi ket qua.",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
  {
    key: "encourage-hard-mouth-compensation",
    name: "Khuyen khich kieu ngoai mieng cung nhung dang tu va si dien",
    type: "encourage",
    severity: "low",
    description: "Sau khi bi hung hoac thua the, nhan vat co the dung mieng cung, lai chuyen hoac tu chua chay de giu the dien.",
    detectPatterns: [],
    rewriteSuggestion: "Cho nhan vat them mot cau cung mieng, tu bao chua hoac doi huong de va mat mui.",
    promptInstruction: "Khi nhan vat bi que hoac hut the, co the de ho dung mieng cung, danh trong lang hoac tu hop ly hoa de va si dien.",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
  {
    key: "encourage-life-noise",
    name: "Khuyen khich tieng on doi song",
    type: "encourage",
    severity: "low",
    description: "Co the them vua phai nhung tieng on hoac chi tiet sinh hoat khong hoan toan phuc vu chu tuyen de tang cam giac hien truong.",
    detectPatterns: [],
    rewriteSuggestion: "Bu them tieng dong moi truong, tap am, mot quang ngat nho hoac cac chi tiet sinh hoat vun.",
    promptInstruction: "Giu lai vua phai tieng on doi song va thong tin khong hoan toan huu dung de tang cam giac co mat trong canh.",
    autoRewrite: false,
    enabled: true,
    globalBaselineEnabled: false,
  },
];
